spring.application.name=OrderSystem
spring.datasource.url=jdbc:mysql://localhost:3306/ordersystem?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=yourpassword


# Hibernate properties